FROM nginx

COPY src /usr/share/nginx/html

ARG fastcgiconturi

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_conf.tpl nginx_conf.tpl

RUN echo "Attaching to: ${fastcgiconturi}"
RUN sed s/fastcgiconturi/${fastcgiconturi}/g nginx_conf.tpl > /etc/nginx/conf.d/site.conf

EXPOSE 80
